# Travis CI configuration file for running tests
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

branches:
  only:
    - laq/travisTest
services:
  - mongodb

notifications:
  email: false
before_install: 
  - pip list
  - sudo apt-get update -qq
 # - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-nose python-httplib2 python-httplib2 python-gdbm python-tk
 # - pip install --upgrade pip
 # - sudo pip install --upgrade virtualenv
 # - sudo apt-get install -y build-essential software-properties-common python-software-properties libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev
 # - sudo apt-get install -y python-numpy=1.6.2
  - sudo apt-get install -q -y gfortran libblas-dev liblapack-dev
  - sudo apt-get install -q python-scipy
install:
 - ./info.sh
  # - pip install Paver==1.2.1
 - pip install -q -r requirements/edx/pre.txt
 - pip install -q -r requirements/edx/paver.txt
 - pip install -q -e .
 #Following 2 hack for nltk https://github.com/nltk/nltk/issues/824
 - pip install setuptools==9.1
 - pip install -U nltk
 # - pip list
 - pip install -r requirements/edx/github.txt
 - pip install coverage==3.7 
 # - pip install PyContracts==1.6.5
 - pip install -q -r requirements/edx/local.txt
 - pip install -r requirements/edx/base.txt
 # - pip install -r requirements/edx/post.txt
 - echo "{}" > /home/travis/build/lms.env.json
 # - pip install -r requirements/edx/pre.txt
 # - pip install -r requirements/edx/base.txt
script:
  # - paver test_system -s lms
  - ./info.sh
  - paver travis
  - paver test_system -s lms
  # - paver test

