# Travis CI configuration file for running tests
language: python
python:
  - "2.7"

branches:
  only:
    - laq/travisTest
services:
  - mongodb

notifications:
  email: false
before_install: # Installing scipy deps: http://stackoverflow.com/a/14541175
 # - sudo apt-get update
 # - sudo pip install --upgrade pip
 # - sudo pip install --upgrade virtualenv
 # - sudo apt-get install  gfortran libopenblas-dev liblapack-dev
 # - sudo apt-get install -y build-essential software-properties-common python-software-properties libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev
install:
 - pip install -r requirements/edx/paver.txt
 - echo "{}" > /home/travis/build/lms.env.json
 # - pip install -r requirements/edx/pre.txt
 # - pip install -r requirements/edx/base.txt
script:
  - paver test_system -s lms

