# Travis CI configuration file for running tests
language: python
branches:
  only:
    - laq/travisTest
services:
  - mongodb

notifications:
  email: false
python:
  - "2.7"
before_install: # Installing scipy deps: http://stackoverflow.com/a/14541175
 - sudo apt-get update
 - sudo pip install --upgrade pip
 - sudo pip install --upgrade virtualenv
 # - sudo apt-get install -qq gfortran libopenblas-dev liblapack-dev
install:
  #- "sudo apt-get install -y build-essential software-properties-common python-software-properties curl git-core libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev tree"
 - pip install -r requirements/edx/paver.txt
script:
  - paver test

