# Travis CI configuration file for running tests
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

branches:
  only:
    - laq/travisTest
services:
  - mongodb


env:
  - TEST_SYSTEM=lms
  - TEST_SYSTEM=cms

notifications:
  email: false
before_install: 
  #- pip list
  - sudo apt-get update -qq
 # - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-nose python-httplib2 python-httplib2 python-gdbm python-tk
 # - pip install --upgrade pip
 # - sudo pip install --upgrade virtualenv
 # - sudo apt-get install -y build-essential software-properties-common python-software-properties libxml2-dev libxslt1-dev libfreetype6-dev python-pip python-apt python-dev
  - sudo apt-get install -qq -y gfortran libblas-dev liblapack-dev
  - sudo apt-get install -qq python-scipy
install:
 - ./info.sh
  # - pip install Paver==1.2.1
 - pip install -qq -r requirements/edx/pre.txt
 - pip install -qq -r requirements/edx/paver.txt
 - pip install -qq -e .
 #Following 2 hack for nltk https://github.com/nltk/nltk/issues/824
 - pip install -qq setuptools==9.1
 - pip install -qq -U nltk
 # - pip list
 - travis_wait pip install -qq -r requirements/edx/github.txt
 - pip install -qq coverage==3.7 
 # - pip install PyContracts==1.6.5
 - pip install  -qq -r requirements/edx/local.txt
 - pip install -q -r requirements/edx/base.txt
 # - pip install -r requirements/edx/post.txt
 - echo "{}" > /home/travis/build/lms.env.json
script:
  # - paver test_system -s lms
  #- ./info.sh
  #- paver travis
  - paver test_system -s $TEST_SYSTEM --fasttest
  # - paver test

